remote_theme: nextzlog/pafe
url: https://nextzlog.dev
name: 無線部開発班
icon: /assets/head.png
lead: The University of Tokyo Amateur Radio Club System Development Task Force
desc: &lead
items:
- name: コンテスト運営システム
  href: /ats4
- name: リアルタイムコンテスト
  href: /real
links:
- name: Twitter
  href: https://twitter.com/nextzlog
  icon: fab fa-twitter
- name: zLog
  href: https://zlog.org
- name: 無線部開発班の本
  href: https://book.nextzlog.dev
- name: 東大無線部
  href: https://ja1zlo.u-tokyo.org
jumps:
- name: autodyne
  href: https://github.com/autodyne
  icon: fab fa-github
- name: nextzlog
  href: https://github.com/nextzlog
  icon: fab fa-github
plugins:
- jekyll-sitemap
