on:
  push:
    branches:
    - 'master'
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/configure-pages@v2
    - uses: actions/jekyll-build-pages@v1
    - uses: actions/upload-pages-artifact@v1
  Publish:
    needs: Prepare
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - uses: actions/deploy-pages@v1
